[package]
name = "fast2d"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/FastWaveViewer/Fast2D"
authors = ["Martin Kavík <martin@kavik.cz>"]
description = "Draw shapes and text using Canvas Web API or wgpu"
categories = ["Graphics"]
license = "UPL-1.0"
readme = "../README.md"

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[dependencies]
chumsky = { version = "1.0.0-alpha.8", features = ["pratt", "serde"] }
ariadne = "0.5"
pin-project = "1"
serde_json_any_key = "2.0.0"

ulid = { version = "1.2.0", features = ["serde"] }
# `rustflags = ["--cfg", 'getrandom_backend="wasm_js"']` has to be in workspace .cargo/config.toml
getrandom = { version = "0.3", features = ["wasm_js"] }

zoon = { git = "https://github.com/MoonZoon/MoonZoon", rev = "d3333db9ebe52c49117858927df5c73f9d9b2dae" }
